set(command "/usr/local/Cellar/cmake/3.22.1/bin/cmake;-P;/Users/ahiggins/src/apache/arrow/cpp/src/xsimd_ep-stamp/download-xsimd_ep.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "/usr/local/Cellar/cmake/3.22.1/bin/cmake;-P;/Users/ahiggins/src/apache/arrow/cpp/src/xsimd_ep-stamp/verify-xsimd_ep.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "/usr/local/Cellar/cmake/3.22.1/bin/cmake;-P;/Users/ahiggins/src/apache/arrow/cpp/src/xsimd_ep-stamp/extract-xsimd_ep.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
